import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {GlobalNav} from "@/ui/global-nav";
import {AddressBar} from "@/ui/address-bar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`${inter} antialiased bg-gray-1100 overflow-y-scroll bg-[url('/grid.svg')] pb-36`}>
        <GlobalNav/>

        <div className="lg:pl-72">
            <div className="mx-auto max-w-4xl space-y-8 px-2 pt-20 lg:px-8 lg:py-8">
                <div className="bg-vc-border-gradient rounded-lg p-px shadow-lg">
                    <div className="rounded-lg bg-black">
                        <AddressBar/>
                    </div>
                </div>

                <div className="bg-vc-border-gradient rounded-lg p-px shadow-lg shadow-black/20">
                    <div className="rounded-lg bg-black p-3.5 lg:p-6">{children}</div>
                </div>
            </div>
        </div>
        </body>
        </html>
    )
}
